server:
  port: 8080


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost8761/eureka


spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        #Route Mapping
        - id: authentication-service
          uri: http://localhost:8095/
          predicates:
            - Path=/authentication/**
          filters:
            - RewritePath=/authentication(?<segment>/?.*), $\{segment}

            #Route Mapping

        #Route Mapping
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user(?<segment>/?.*), $\{segment}



